### ISSUE TITLE
Помогите разобраться

### ISSUE THREAD

**Issue by Santyago52** [ds-voix/xswitcher#10]
Здравствуйте!
У меня linux mint cinamon 21. Скачал bin и conf. К сожалению я не понял где conf файле настройка отвечающая за кнопку переключения. Пользовался всеми дефолтными настройками. Запускаю от рута, с указанием конфига. Показывает переключения программ, пытаюсь вводить текст и переключить с помощью клавиши Break. Но ничего не происходит. Однажды раскладка таки поменялась, но введённый ранее текст не исправился. Пробовал в различных программах.
Помогите, пожалуйста!

**Comment by ds-voix** [comment]
>  настройка отвечающая за кнопку переключения

```
[Actions]
 "Action.CyclicSwitch" = [ "OFF:(R_CTRL|ALT|META|SHIFT)  SEQ:(L_CTRL:1,L_CTRL:0)" ] # Single short LEFT CONTROL

```
>  Однажды раскладка таки поменялась, но введённый ранее текст не исправился.

У Вас гном. Нужно скачать/собрать/установить https://github.com/lyokha/g3kb-switch
Дальше использовать конфиг из папки "gnome3", установив switch.gnome в "/usr/local/bin/" и дав права на запуск.
Дальше позапускать пару раз "switch.gnome" и убедиться что раскладка переключается.
После этого заработает и xswitcher. Но с заметными тормозами, т.к. переключает не напрямую командой в X (которую перехватывает гном), а отправкой сообщений через шину dbus (тормозную).

* Если это всё слишком сложно, попробуйте поискать чью-нибудь готовую сборку в ppa (в терминологии ubuntu). Или как это называется для linux mint.

Удачи!
