### ISSUE TITLE
Проблемы с KVM.

### ISSUE THREAD

**Issue by georgehazan** [ds-voix/xswitcher#11]
Есть линуксовая тачка, на которой в сессии крутится xswitcher. Машина присоединена к KVM, который шарит клаву, мышь и монитор между 4 компами. Каждый раз, когда машинка с xswitcher перестает быть текущей, xswitcher падает

$ killall xswitcher && ~/Utils/xswitcher 
Config error: unable to open config file: open /etc/xswitcher/xswitcher.conf: no such file or directory
* Using defaults!
keyboard: Power Button
keyboard: Power Button
keyboard: Canyon CNS-CWC5 Webcam: Canyon 
mouse:  USB OPTICAL MOUSE
keyboard: keybd interface
keyboard: Microsoft Wired Keyboard 600
mouse: Microsoft Wired Keyboard 600 Consumer Control
keyboard: Microsoft Wired Keyboard 600 System Control
keyboard: Eee PC WMI hotkeys
Closing device "keybd interface" due to an error:
""" read /dev/input/event22: no such device """
= konsole

Closing device " USB OPTICAL MOUSE" due to an error:
""" read /dev/input/event2: no such device """
Closing device "Microsoft Wired Keyboard 600" due to an error:
""" read /dev/input/event3: no such device """
Closing device "Microsoft Wired Keyboard 600 Consumer Control" due to an error:
""" read /dev/input/event4: no such device """
Closing device "Microsoft Wired Keyboard 600 System Control" due to an error:
""" read /dev/input/event5: no such device """

Как бы сделать так, чтобы при принятии фокуса xswitcher либо перечитывал бы список устройств, либо просто перезапускался бы?

**Comment by ds-voix** [comment]
Насколько вижу, xswitcher не падает а просто теряет отключенные устройства.
Думаю что тут напрашивается повесить inotify() на " /dev/input/".

Займусь после окончания апгрейда своих локалхостов до последней openSUSE. Там ещё одну проблему подвезли, ломающую respawn в процессе старта KDE.

**Comment by georgehazan** [comment]
@ds-voix  нету новостей?

**Comment by ds-voix** [comment]
Попробуйте последний коммит.
xswitcher теперь перезапускается через 1с после подключения нового устройства ввода.

**Comment by georgehazan** [comment]
@ds-voix пашет, но теперь почему-то только от рута

$ ~/Utils/xswitcher &
* Using defaults!
permission error for /dev/uinput try cmd : sudo chmod +0666 /dev/uinput

Старый вариант преспокойно пинается от имени юзера

**Comment by ds-voix** [comment]
Он и раньше работал так же. В инструкции написано про выставление suid-бита (разрешения 1755 в восьмеричной записи).
```
sudo chown root:root /usr/local/bin/xswitcher
sudo chmod +xs /usr/local/bin/xswitcher
```
Альтернативно в linux аналогичный эффект можно получить через setcaps. Но мне лень т.к. сложнее и без видимого выигрыша в безопасности _(для данного применения)_.
:asterisk: На досуге можно подумать над заменой suid на sgid. Но это — "дистрозависимо".
* А вот назначать "0666" на доступ к устройствам ввода — однозначно несчастливый подход.

**Comment by georgehazan** [comment]
> В инструкции написано про выставление suid-бита

Файл что ли стерся при копировании?.. интересно
В любом случае работает, третий раз кряду уже. Спасибо :-)
