### ISSUE TITLE
Не правильно работает.

### ISSUE THREAD

**Issue by juf00th** [ds-voix/xswitcher#14]
Debian 12.5

Если выбрать например не правильную раскладку (EN), набрать текст, нажать паузу и далее сколько угодно ее нажимать текст "перенабирается" в ту же самую не правильную раскладку. Далее набрать еще текст, вот он уже правильно "перенабирается" поочередно в разные раскладки.

**Comment by ds-voix** [comment]
Для пользователей gnome *(который в debian по умолчанию, а иного вы не указали)* подготовлена часть инструкции "Gnome is the pain".
Нормальное переключение там умышленно сломано. Необходимо использовать "костыли" из https://github.com/ds-voix/xswitcher/tree/main/gnome3.
