### ISSUE TITLE
Переключения по shift_L and shift_R

### ISSUE THREAD

**Issue by Pro-pra** [ds-voix/xswitcher#15]
Пользователь сообщил что после обновления перестал работать его вариант переключения "переключение происходит по шифтам раздельно: левый шифт одна раскладка, правый соответственно другая"

тема на форуме https://forum.rosalinux.ru/viewtopic.php?f=48&t=11163

**Comment by ds-voix** [comment]
Откуда ж я знаю, какая у "пользователя" конфигурация (можно посмотреть "xswitcher -d").
И что за обновление, когда релиз был один. Последний опубликованный бинарник? Своя сборка?
Подсказка: xswitcher делает ровно то что настроено в конфигурации.
Я, чтобы так работало, добавил в конфигурацию по умолчанию:
```
 "Action.Layout0" = [ "OFF:(CTRL|ALT|META|R_SHIFT)  SEQ:(L_SHIFT:1,L_SHIFT:0)" ] # Single short LEFT SHIFT
 "Action.Layout1" = [ "OFF:(CTRL|ALT|META|L_SHIFT)  SEQ:(R_SHIFT:1,R_SHIFT:0)" ] # Single short RIGHT SHIFT
…
[Action.Layout0] # Direct layout selection
 Action = [ "Layout" ] # Internal layout selection func
 Layout = 0

[Action.Layout1] # Direct layout selection
 Action = [ "Layout" ] # Internal layout selection func
 Layout = 1
```
* Кроме gnome. Для него — отдельные костыли.
* При отсутствии Xorg, нужно придумывать способ командовать переключние. Без "X", xswitcher вряд ли заработает, т.к. слинкован с Xlib etc.

**Comment by ds-voix** [comment]
Закрываю тикет в связи с отсутствием фидбэка.

**Comment by Pro-pra** [comment]
Юзер написал такое на форуме:
```
После непродолжительных ковыряний и изысканий все же xswitcher заработал. Почему-то бинарник в /usr/bin не имел рут-прав, чего ему не хватает для правильной работы. Удаление/переустановка через dnfdragora не помогали. Дал рут-права:
chown root:root xswitcher
chmod +xs xswitcher
помогло.
```
