### ISSUE TITLE
В окне удаленного доступа через NoMachine не работает.

### ISSUE THREAD

**Issue by megadalp** [ds-voix/xswitcher#4]
xswitcher запущен на ноуте, на нем переключения работают, и в режиме -t все нажатия на экран валятся, как и обещано.

А когда подключился к нему через NoMachine, нажатия с удаленного компа проходить перестали. Вообще все. :( Где-то потерялись.

Забавно, что все равно на ноутбуке я не могу полноценно пользоваться xswitcher - на клавиатуре нет кнопки Pause/Break. :)
В свое время по этой же причине в PuntoSwitcher пришлось менять дефолтную (эту же) кнопку на ту, которая есть везде.
И я не одинок, наверное. М.б., все же какую-то другую назначить? Хоть через конфиг.

**Comment by ds-voix** [comment]
Попробуйте прочитать [xswitcher.conf](https://github.com/ds-voix/xswitcher/blob/main/xswitcher.conf) (тот самый конфиг).
Особое внимание на **"Action.RetypeWord"** (и да, комбинаций может быть несколько и в конфиге их две т.к. у меня самого Lenovo TP X1 с недо-клавиатурой).

* Если подключаетесь к удалённому рабочему столу, xswitcher должен быть запущен на **локальном** конце.
Ну вот зачем вам глюки от конкуренции виртуальных клавиатур на той стороне?
* Через хуки xswitcher можно заставить работать с любыми окнами, поддерживающими хоть какой-то интерфейс переключения. Например, с VNC xswitcher работает, а xneur просто ломал ввод. Но иногда нужно приспосабливаться к какому-то особенному API. Как в случае работы с Gnome.

**Comment by megadalp** [comment]
Да, теперь увидел - т.е. он F12 уже понимает?  Это отлично.

> Если подключаетесь к удалённому рабочему столу,
> xswitcher должен быть запущен на локальном конце.

с этим проблемка :(
Клиент (локальный конец) - Windows 10. :)) Пытаюсь (в очередной раз) перейти на линукс, настраиваю kubuntu. Вот искал замену Punto.

В любом случае, спасибо! За программу и за ответ.
Когда (и если) я окончательно перееду на линух, обязательно вернусь к xswitcher.
