### ISSUE TITLE
External BT keyboard

### ISSUE THREAD

**Issue by stsg** [ds-voix/xswitcher#6]
Внешняя блутус клавиатура:

`/dev/input/event19:     Keychron K6`

определяется как мышь:
```
❯ ./bin/xswitcher -t

keyboard: Power Button
keyboard: Ideapad extra buttons
mouse: 06CBCD3E:00 06CB:CE78 Mouse
mouse: 06CBCD3E:00 06CB:CE78 Touchpad
mouse: Logitech Wireless Mouse MX Master 3
mouse: Keychron K6
jhjhjhjh
```
как исправить?

**Comment by ds-voix** [comment]
Попробуйте последнюю сборку (commit d8e3f06aee96fe81db87c6aaa96980df1508a2d7).
Устройство определяется как "мышь" если объявляет "мышиные" события. Как клавиатура — если "клавиатурные" события. Но может быть и тем и этим. Я это исправил в последнем коммите.

**Comment by stsg** [comment]
Спасибо!
Помогло!
