### ISSUE TITLE
IDE от JetBrains перехватывают все нажатия раньше чем xswitcher?

### ISSUE THREAD

**Issue by KrasilnikovKB** [ds-voix/xswitcher#8]
с настройками по умолчанию и в PhpStorm и в xswitcher - переключения клавиатуры (и настроенные хуки) не работают только в их IDE :(

Есть идеи как победить?

Fedora workstation KDE

**Comment by ds-voix** [comment]
Проблема вот в этом куске конфигурации:
```
[[WindowClasses]]
 # VNC, VirtualBox, qemu etc. emulates there input independently, so never intercept.
 # With the exception of some stupid VNC clients, which does high-level (layout-based) keyboard input.
 Regex = "^(VirtualBox|Focus-Proxy-Window)"
 Actions = "" # Do nothing while focus stays in VirtualBox | ATEN-based java VNC-console

```
Могу ошибаться, но похоже что "Focus-Proxy-Window" — это любое "графическое" java-приложение. Мне это мешало т.к. переход на русскую (точнее, не-ASCII) раскладку вводит в ступор jre-клиентов vnc (ipmi и "коммерческие аналоги" idrac, ilo etc.).
Вытрите "`|Focus-Proxy-Window`" из конфигурации, или закомментируйте/удалите этот раздел вообще.
Перезапустите xswitcher с новой конфигурацией, и оно заработает.

* _У меня самого есть экземпляр pycharm-community, но до сих пор не замечал т.к. использовал его только для навигации по одному развесистому проекту. Подумаю, что тут можно сделать…_

**Comment by KrasilnikovKB** [comment]
Да. удалил из регулярки `|Focus-Proxy-Window` и жизнь наладилась.

**Comment by KrasilnikovKB** [comment]
Добавлю тут из своих пожеланий: может оно войдёт когда то в официальный релиз, а не будет сделано на уровне костылей, как это сделал я :)

сделал отдельный экшен на долгое нажатие PAUSE - перевод выделенного текста в другую раскладку + смена раскладки клавиатуры:
```
"Action.Hook1" = [ "OFF:(CTRL|ALT|META|SHIFT)  SEQ:(PAUSE:2,PAUSE:0)" ]
...
[Action.Hook1] # Run external commands
  Action = [ "Action.CyclicSwitch", "Exec" ]
  Exec = "/usr/local/bin/translate_selected_text.sh"
```

**/usr/local/bin/translate_selected_text.sh:**
```
#!/bin/bash
#
# предварительно установить xdotool и xsel
#
xdotool key Ctrl+Insert
#sleep 0.3s
xsel -bo | sed "y/abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ[]{};':\",.\/<>?@#\$^&\`~фисвуапршолдьтщзйкыегмцчняФИСВУАПРШОЛДЬТЩЗЙКЫЕГМЦЧНЯхъХЪжэЖЭбюБЮ№ёЁ/фисвуапршолдьтщзйкыегмцчняФИСВУАПРШОЛДЬТЩЗЙКЫЕГМЦЧНЯхъХЪжэЖЭбю.БЮ,\"№;:?ёЁabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ[]{};':\",.<>#\`~/" | xsel -bi
#sleep 0.3s
xdotool key Shift+Insert

```

т.о. имею: 

- при коротком нажатии PAUSE - исправляется последнее введённое слово
- при долгом нажатии PAUSE - исправляется выделенный текст

**Comment by ds-voix** [comment]
Шансов очень мало, если сами такую функциональность не напишете. То что сейчас есть, представляет собой универсальный _(ну, почти)_ скелет, работающий с любыми па́рами языков с фонетической записью. И не ломается на дополнительных "рядах" (если правильно сконфигурировано). _Мне теперь хорошо и нет стимула тратить время._

То что Вы хотите, привязывается к конкретным языкам. _(И может ломаться на всяких "compose", нужно разбираться)._
Могу подсказать примерный алгоритм как сделать более-менее универсально (но для XOrg и Wayland придётся, наверное, писать разные реализации).

Пишем функциональность настройки на заданные в конфиге номера локалей. Примерно так:
- Создать окно с контекстом ввода и переключить туда фокус.
- С виртуальной клавиатуры послать нажатие всех символов основного наборного поля, друг за другом. Выделить/скопировать результат. Сложить в хэш-таблицу "символ = номер", и наоборот (для быстрого поиска "оттуда" и трансляции "туда").
- Повторить для каждой из локалей.

Теперь для любого поля ввода с доступной функциональностью "вырезать/вставить" и поддерживающего для этого хоткеи  можно "вырезать" текст к себе в буфер, посимвольно заменить "символ = номер" из текущей локали на "номер = символ" из желаемой _(не найдено — не трогаем, переходим к следующему)_ и "вставить" полученное обратно.

Удачи!
